server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_DEV}
    username: ${DB_USER_DEV}
    password: ${DB_PASS_DEV}

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
